# server
server.port=8086
spring.application.name=notification-service

# ActiveMQ 5.x
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

# Mail (use your SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mitchemorgan@gmail.com
spring.mail.password=rljr cuzb xocs jgdj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.ticket.serviceBaseUrl=http://localhost:8081
app.mail.from=no-reply@ticketing.local
app.mail.managerEmail=mitchemorgan@gmail.com
app.pdf.outDir=${java.io.tmpdir}/ticket-pdfs


# JMS queue names
app.jms.queues.ticketCreated=ticket.created
app.jms.queues.ticketResolved=ticket.resolved
app.jms.queues.autocloseResolved=ticket.autoclose